name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: > 
          --health-cmd="curl -s http://localhost:9000/api/system/health | grep -q 'UP'" --health-interval=10s --health-timeout=5s --health-retries=10
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for analysis
      - name: Wait for SonarQube to be ready
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:9000); do
            echo 'Waiting for SonarQube...'
            sleep 10
          done
      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"
